// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Head = require("next/head");

function WelcomePage$default(Props) {
  return React.createElement("div", undefined, React.createElement(Head.default, {
                  children: React.createElement("title", undefined, "Welcome")
                }), "Welcome to Next");
}

var $$default = WelcomePage$default;

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
